"""rename4

Revision ID: 0147342d6898
Revises: a8d21437defe
Create Date: 2022-01-07 16:42:52.787991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0147342d6898'
down_revision = 'a8d21437defe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('photo_ibfk_2', 'photo', type_='foreignkey')
    op.drop_column('photo', 'rate_id')
    op.add_column('rating', sa.Column('photo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rating', 'photo', ['photo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.drop_column('rating', 'photo_id')
    op.add_column('photo', sa.Column('rate_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('photo_ibfk_2', 'photo', 'rating', ['rate_id'], ['id'])
    # ### end Alembic commands ###
