"""relation rating-user

Revision ID: 02b0dd00f379
Revises: ef02f17b80c0
Create Date: 2022-01-04 17:24:29.483440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02b0dd00f379'
down_revision = 'ef02f17b80c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rating', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.drop_column('rating', 'user_id')
    # ### end Alembic commands ###
