"""add relationship user-photo

Revision ID: 07cc3458fd6d
Revises: 
Create Date: 2021-12-28 17:19:50.217650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07cc3458fd6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('data_posted', sa.DateTime(), nullable=True))
    op.add_column('photo', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'photo', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photo', type_='foreignkey')
    op.drop_column('photo', 'user_id')
    op.drop_column('photo', 'data_posted')
    # ### end Alembic commands ###
