"""tag_users

Revision ID: 200136554318
Revises: 62b2d3da9284
Create Date: 2022-01-13 14:37:18.525286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '200136554318'
down_revision = '62b2d3da9284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tag',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tag')
    # ### end Alembic commands ###
