"""abcbvv

Revision ID: 3462d8c51013
Revises: a6b0c1076616
Create Date: 2022-01-17 23:39:35.358745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3462d8c51013'
down_revision = 'a6b0c1076616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('photo_tag_ibfk_1', 'photo_tag', type_='foreignkey')
    op.create_foreign_key(None, 'photo_tag', 'photo', ['photo_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photo_tag', type_='foreignkey')
    op.create_foreign_key('photo_tag_ibfk_1', 'photo_tag', 'photo', ['photo_id'], ['id'])
    # ### end Alembic commands ###
