"""abcbvvs

Revision ID: 440043aaebc8
Revises: 3462d8c51013
Create Date: 2022-01-17 23:42:24.042130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440043aaebc8'
down_revision = '3462d8c51013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_ibfk_2', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'], ondelete='cascade')
    op.drop_constraint('photo_ibfk_1', 'photo', type_='foreignkey')
    op.create_foreign_key(None, 'photo', 'user', ['user_id'], ['id'], ondelete='cascade')
    op.drop_constraint('rating_ibfk_2', 'rating', type_='foreignkey')
    op.create_foreign_key(None, 'rating', 'user', ['user_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.create_foreign_key('rating_ibfk_2', 'rating', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'photo', type_='foreignkey')
    op.create_foreign_key('photo_ibfk_1', 'photo', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_ibfk_2', 'comment', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
