"""delete tag_user

Revision ID: 6bd245e09ff0
Revises: 91cd200a8a7a
Create Date: 2022-01-06 15:45:24.402902

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6bd245e09ff0'
down_revision = '91cd200a8a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tag',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='user_tag_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_tag_ibfk_2'),
    sa.PrimaryKeyConstraint('user_id', 'tag_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
