"""abcb

Revision ID: a6b0c1076616
Revises: 190dd6ded744
Create Date: 2022-01-17 23:37:09.982823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b0c1076616'
down_revision = '190dd6ded744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_ibfk_1', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'photo', ['photo_id'], ['id'], ondelete='cascade')
    op.drop_constraint('rating_ibfk_3', 'rating', type_='foreignkey')
    op.create_foreign_key(None, 'rating', 'photo', ['photo_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.create_foreign_key('rating_ibfk_3', 'rating', 'photo', ['photo_id'], ['id'])
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_ibfk_1', 'comment', 'photo', ['photo_id'], ['id'])
    # ### end Alembic commands ###
