"""rename3

Revision ID: a8d21437defe
Revises: cbdaac3a7987
Create Date: 2022-01-07 16:40:52.039261

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8d21437defe'
down_revision = 'cbdaac3a7987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('rate_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'photo', 'rating', ['rate_id'], ['id'])
    op.drop_constraint('rating_ibfk_1', 'rating', type_='foreignkey')
    op.drop_column('rating', 'photo_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('photo_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('rating_ibfk_1', 'rating', 'photo', ['photo_id'], ['id'])
    op.drop_constraint(None, 'photo', type_='foreignkey')
    op.drop_column('photo', 'rate_id')
    # ### end Alembic commands ###
