"""join_data

Revision ID: c199b97cee59
Revises: 200136554318
Create Date: 2022-01-14 18:17:15.668889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c199b97cee59'
down_revision = '200136554318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('join_data', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'join_data')
    # ### end Alembic commands ###
