"""rating -> ratings

Revision ID: ef02f17b80c0
Revises: feb314f3b510
Create Date: 2022-01-04 15:20:04.998567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef02f17b80c0'
down_revision = 'feb314f3b510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('ratings', sa.Integer(), nullable=True))
    op.drop_column('rating', 'rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('rating', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('rating', 'ratings')
    # ### end Alembic commands ###
